name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Or your default branch name (could be 'master')
  workflow_dispatch:    # Allows manual trigger from GitHub UI

permissions:
  contents: write       # Needed for gh-pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          CI: false  # This prevents treating warnings as errors
          PUBLIC_URL: /letter-recognition-app  # Adjust this if your app is not at the root of the domain
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
